"""Initial migration: create all tables

Revision ID: 46a283a4db6d
Revises: 
Create Date: 2026-02-16 08:30:40.869923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46a283a4db6d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cattle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identification_number', sa.String(), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'FREEMARTIN', name='genderenum'), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SOLD', 'DECEASED', name='statusenum'), nullable=False),
    sa.Column('mother_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mother_id'], ['cattle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cattle_id'), 'cattle', ['id'], unique=False)
    op.create_index(op.f('ix_cattle_identification_number'), 'cattle', ['identification_number'], unique=True)
    op.create_table('statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stat_date', sa.Date(), nullable=False),
    sa.Column('total_cattle', sa.Integer(), nullable=True),
    sa.Column('pregnant_count', sa.Integer(), nullable=True),
    sa.Column('bred_count', sa.Integer(), nullable=True),
    sa.Column('breeding_due_count', sa.Integer(), nullable=True),
    sa.Column('birth_rate', sa.Float(), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statistics_id'), 'statistics', ['id'], unique=False)
    op.create_index(op.f('ix_statistics_stat_date'), 'statistics', ['stat_date'], unique=True)
    op.create_table('breeding_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cattle_id', sa.Integer(), nullable=False),
    sa.Column('breeding_date', sa.Date(), nullable=False),
    sa.Column('semen_id', sa.String(), nullable=True),
    sa.Column('result', sa.Enum('PENDING', 'PREGNANT', 'FAILED', name='breedingresultenum'), nullable=False),
    sa.Column('result_check_date', sa.Date(), nullable=True),
    sa.Column('expected_calving_date', sa.Date(), nullable=True),
    sa.Column('actual_calving_date', sa.Date(), nullable=True),
    sa.Column('birth_type', sa.Enum('EASY', 'DIFFICULT', name='birthtypeenum'), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cattle_id'], ['cattle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_breeding_records_id'), 'breeding_records', ['id'], unique=False)
    op.create_table('cattle_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cattle_id', sa.Integer(), nullable=False),
    sa.Column('note_date', sa.Date(), nullable=False),
    sa.Column('note_type', sa.Enum('SYMPTOM', 'TREATMENT', 'BIRTH', 'OTHER', name='notetypeenum'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cattle_id'], ['cattle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cattle_notes_id'), 'cattle_notes', ['id'], unique=False)
    op.create_table('event_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cattle_id', sa.Integer(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('event_type', sa.Enum('BREEDING_DUE', 'ESTRUS_CHECK', 'PREGNANCY_CHECK', 'BIRTH_DUE', 'BIRTH_OVERDUE', name='eventtypeenum'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cattle_id'], ['cattle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_logs_id'), 'event_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_logs_id'), table_name='event_logs')
    op.drop_table('event_logs')
    op.drop_index(op.f('ix_cattle_notes_id'), table_name='cattle_notes')
    op.drop_table('cattle_notes')
    op.drop_index(op.f('ix_breeding_records_id'), table_name='breeding_records')
    op.drop_table('breeding_records')
    op.drop_index(op.f('ix_statistics_stat_date'), table_name='statistics')
    op.drop_index(op.f('ix_statistics_id'), table_name='statistics')
    op.drop_table('statistics')
    op.drop_index(op.f('ix_cattle_identification_number'), table_name='cattle')
    op.drop_index(op.f('ix_cattle_id'), table_name='cattle')
    op.drop_table('cattle')
    # ### end Alembic commands ###
