"""add is_active column

Revision ID: 00f900e6dddf
Revises: e432ef3fb463
Create Date: 2026-03-09 23:35:31.953342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00f900e6dddf'
down_revision = 'e432ef3fb463'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('breeding_records', sa.Column('is_active', sa.Integer(), nullable=True))
    op.add_column('cattle', sa.Column('is_active', sa.Integer(), nullable=True))
    op.add_column('event_logs', sa.Column('is_active', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_logs', 'is_active')
    op.drop_column('cattle', 'is_active')
    op.drop_column('breeding_records', 'is_active')
    # ### end Alembic commands ###
