"""add father_kpn

Revision ID: e432ef3fb463
Revises: a1b2c3d4e5f6
Create Date: 2026-03-09 23:19:52.988834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e432ef3fb463'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cattle', sa.Column('father_kpn', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cattle', 'father_kpn')
    # ### end Alembic commands ###
